[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CNN for Alzheimer and control"
authors = [{name = "Laura", email = "l.toni7@studenti.unipi.it"}]
dynamic = ["version", "description"]
