version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
  lint-and-coverage:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Linter
          command: |
            flake8 src/
            flake8 test/
      - run:
          name: Coverage
          command: |
            coverage run
            coverage report
      - store_test_results:
         path: test-results
workflows:
  main:
    jobs:
      - build-and-test